version: '3'
services:
  go:
    build: ./webapp/go
    volumes:
      - .:/app
    ports:
      - 127.0.0.1:5555:5555
      - 127.0.0.1:7000:7000
      - 127.0.0.1:8000:8000
      - 127.0.0.1:6060:6060
      - 127.0.0.1:10022:22
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASS=secret
    security_opt:
      - seccomp:unconfined
    deploy:
      resources:
        limits:
          cpus: '3.0'
  db:
    image: mysql:5.7
    volumes:
      - ./webapp/sql:/docker-entrypoint-initdb.d
      - ./webapp/sql/conf:/etc/mysql/conf.d
      - ./datadir:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_HOST=127.0.0.1
      - MYSQL_USER=root
      - MYSQL_PASS=secret
    security_opt:
      - seccomp:unconfined
    ports:
      - 127.0.0.1:3306:3306
      - 127.0.0.1:20022:22
    deploy:
      resources:
        limits:
          cpus: '2.0'
  golang:
    image: golang:1.14.6
    volumes:
      - .:/app
    working_dir: /app
    command: /bin/sh -c "while sleep 1000; do :; done"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=secret
    links:
      - db
    ports:
       - 8080:80
    volumes:
       - /sessions
